HRBMSWEBAPP/Controllers/BookingController.cs
using HRBMSWEBAPP.Data;
using HRBMSWEBAPP.Models;
using HRBMSWEBAPP.Repository;
using HRBMSWEBAPP.Service;
using HRBMSWEBAPP.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace HRBMSWEBAPP.Controllers
{
    //[Authorize(Roles ="Admin, User")]
    public class BookingController : Controller
    {
        private UserManager<ApplicationUser> _userManager;
        private readonly IBookingDBRepository _repo;
       
        IRoomDBRepository _Roomrepo;
        private readonly IUserService _UserService;
        HRBMSDBCONTEXT _context;

        public BookingController(IBookingDBRepository repo, IRoomDBRepository Roomrepo, 
                                 HRBMSDBCONTEXT context, UserManager<ApplicationUser> userManager,
                                 IUserService userService)
        {
            this._repo = repo;
            _Roomrepo = Roomrepo;
            _context = context;
            _userManager = userManager;
            _UserService = userService;
        }


        public async Task<IActionResult> GetAllBookings(string searchString)
        {
          

            var booklist = from books in _repo.GetAllBooking1()
                           select books;
            if (!String.IsNullOrEmpty(searchString))
            {
                booklist = booklist.Where(s => s.User.Full_Name.ToLower().Contains(searchString.Trim().ToLower()));
                return View(booklist.ToList());
            }
            // use access token to call a protected web API
            var token = HttpContext.Session.GetString("JWToken");
            List<Booking> book = await this._repo.GetAllBooking(token);
            return View(book);
            //List <Booking> booking = await this._repo.GetAllBooking();
            //return View(booking);
        }

       
        public async Task<IActionResult> Details(int? id)
        {


            if (id == null)
            {
                return NotFound();
            }

         
            Booking booking = await this._repo.GetBookingById((int)id);
            return View(booking);
        }


   
        public async Task<IActionResult> Delete(int id)
        {
        
            // Check if the booking exists
            var booking = await this._repo.GetBookingById(id);
            if (booking == null)
            {
                return NotFound();
            }
            var token = HttpContext.Session.GetString("JWToken");
            var room = await this._Roomrepo.GetRoomById(booking.RoomId);
            if (room != null)
            {
                room.Status = true;
                _context.Room.Update(room);
                _context.SaveChanges();
            }
            // Delete the booking from the database
            await this._repo.DeleteBooking(id, token);

            // Redirect to the list of bookings
            return RedirectToAction("GetAllBookings");
        }

        [HttpGet]
        public IActionResult Create()
        {
           
            return View();
        }

        [HttpGet]
        public IActionResult CreateRoomBooking(int roomId)
        {
            ViewData["RoomId"] = roomId;
            return View();
        }


        [HttpPost]
        public IActionResult CreateRoomBooking(int roomId, Booking booking)
        {
           

            if (ModelState.IsValid)
            {
                var userId = _UserService.GetUserId();
                booking.UserId = userId;
                booking.RoomId = roomId;
                // Save the booking to the database 
                 _context.Booking.Add(booking);
                _context.SaveChanges();
         
               

                var room = _context.Room.FirstOrDefault(r => r.Id == roomId);
                if (room != null)
                {
                    room.Status = false;
                    _context.Room.Update(room);
                    _context.SaveChanges();
                   
                       
                    
                }


             
                // Redirect to a thank-you page or back to the room list page
                return RedirectToAction("Success");
            }

            ViewData["Message"] = "Data is not valid to create the booking";
            ViewData["RoomId"] = roomId;
            return View();
        }


        [HttpPost]
        public IActionResult Create(Booking booking)
        {
            if (ModelState.IsValid)
            {
                var book = _repo.AddBooking(booking);
           
                return RedirectToAction("GetAllBookings");
            }
            ViewData["Message"] = "Data is not valid to create the booking";
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            List<Room> li = new List<Room>();
            li = _context.Room.ToList();
            ViewBag.listofroom = li;

            List<ApplicationUser> userlist = new List<ApplicationUser>();
            userlist = _userManager.Users.ToList();
            ViewBag.listofUser = userlist;

            var old = await this._repo.GetBookingById(id);
            return View(old);

        }


        [HttpPost]
        public async Task<IActionResult> Update(Booking booking)
        {
            
            await _repo.UpdateBooking(booking.Id,booking);
            return RedirectToAction("GetAllBookings");
        }
        public IActionResult Success()
        {
            return View();
        }
      
        
    }
}

HRBMSWEBAPP/Controllers/RoomCategoryController.cs
using HRBMSWEBAPP.Models;
using HRBMSWEBAPP.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HRBMSWEBAPP.Controllers
{
    //[Authorize(Roles ="Admin, User")]
    public class RoomCategoryController : Controller
    {
        private readonly IRoomCatDBRepository _repo;

        public RoomCategoryController(IRoomCatDBRepository repo)
        {
            this._repo = repo;
        }


        public async Task<IActionResult> GetAllRoomCategories()
        {

            //List<RoomCategories> catlist = await _repo.GetAllRoomCategories();
            //return View(catlist);
            var token = HttpContext.Session.GetString("JWToken");
            List<RoomCategories> categories = await this._repo.GetAllRoomCategories(token);
            return View(categories);


        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            RoomCategories categories = await this._repo.GetRoomCategoriesById((int)id);
            return View(categories);
        }

        public IActionResult Delete(int id)
        {
            var token = HttpContext.Session.GetString("JWToken");
            var cat =  _repo.GetRoomCategoriesById(id);
            if (cat == null)
            {
                return NotFound();
            }
            var catlist = _repo.DeleteRoomCategories(id, token);
            return RedirectToAction("GetAllRoomCategories");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var old = await this._repo.GetRoomCategoriesById(id);
            return View(old);

        }
        [HttpPost]
        public async Task<IActionResult> Update(RoomCategories category)
        {
            await _repo.UpdateRoomCategories(category.Id, category);
            return RedirectToAction("GetAllRoomCategories");
        }

        [HttpPost]
        public IActionResult Create(RoomCategories category)
        {
            if (ModelState.IsValid)
            {
                var cat = _repo.AddRoomCategories(category);
                return RedirectToAction("GetAllRoomCategories");
            }
            ViewData["Message"] = "Data is not valid to create the category";
            return View();
        }

    


      



    }
}

HRBMSWEBAPP/Controllers/RoomController.cs
using HRBMSWEBAPP.Data;
using HRBMSWEBAPP.Models;
using HRBMSWEBAPP.Repository;
using HRBMSWEBAPP.Repository.Rest;
using HRBMSWEBAPP.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http;
using System.Net.Http.Headers;
using TodoMinimalWebApp.Models;

namespace HRBMSWEBAPP.Controllers
{
    //[Authorize(Roles = "Admin, Staff")]
    public class RoomController : Controller
    {
        private readonly IRoomDBRepository _repo;
        private readonly IRoomsRepository _roomsRest;
        HRBMSDBCONTEXT _context;
        private readonly IConfiguration _configs;
        private readonly HttpClient _httpClient;

        public RoomController(IRoomDBRepository repo, HRBMSDBCONTEXT context, IRoomsRepository roomsRest, IConfiguration configs)

        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri("http://localhost:7098/api");
            this._repo = repo;
            _context = context;
            _configs = configs;
            _roomsRest = roomsRest;
        }


        public async Task<IActionResult> GetAllRooms(string searchString)
        {
            var roomlist = from books in _repo.GetAllRoom1()
                           select books;
            if (!String.IsNullOrEmpty(searchString))
            {
                roomlist = roomlist.Where(s => s.Category.Room_Name.ToLower().Contains(searchString.Trim().ToLower()));
                return View(roomlist.ToList());
            }

            // use access token to call a protected web API
            var token = HttpContext.Session.GetString("JWToken");
            List<Room> room = await this._roomsRest.GetAllRooms(token);
            return View(room);

            //List<Room> getallroom = await _repo.GetAllRoom();
            //return View(getallroom);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Room room = await this._repo.GetRoomById((int)id);
            return View(room);
        }


        public async Task<IActionResult> Delete(int id)
        {
            var token = HttpContext.Session.GetString("JWToken");
            var room = await _repo.GetRoomById(id);
            if (room == null)
            {
                return NotFound();
            }
            // Delete the room
            await _roomsRest.DeleteRoom(id, token);
            return RedirectToAction("GetAllRooms");
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = _context.Categories.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Room newRoom)
        {
            if (ModelState.IsValid)
            {
                //consuming rest api
                var token = HttpContext.Session.GetString("JWToken");
                _roomsRest.CreateRoom(newRoom, token);
                //_repo.AddRoom(newRoom);
                return RedirectToAction("GetAllRooms");
            }

            // If ModelState is invalid, collect the validation errors
            var errors = ModelState.Values.SelectMany(v => v.Errors).ToList();
            ViewData["Message"] = "Data is not valid to create the Room";
            ViewBag.Categories = _context.Categories.ToList();
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {

            ViewBag.Categories = _context.Categories.ToList();
            var old = await this._repo.GetRoomById(id);
            return View(old);

        }

        [HttpPost]
        public async Task<IActionResult> Update(Room newRoom)
        {
            var token = HttpContext.Session.GetString("JWToken");
            await _roomsRest.UpdateRoom(newRoom.Id, newRoom, token);
            return RedirectToAction("GetAllRooms");
        }




    }
}

HRBMSWEBAPP/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> _signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HRBMSWEBAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HRBMSWEBAPP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HRBMSWEBAPP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @* @if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="GetAllBookings">Booking</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="GetAllUsers">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="GetAllRoles">Role</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="GetAllRooms">Rooms</a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RoomCategory" asp-action="GetAllRoomCategories">Categories</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Invoice" asp-action="GetAllInvoice">Invoices</a>
                        </li>*@
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Invoice" asp-action="GetAllInvoice">Invoice</a>
                            </li>*@
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Login"><i class="fas fa-user"></i> Sign Up</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Login"><i class="fas fa-sign-in-alt"></i> Login</a>
                            </li>
                        </ul>

                        @*}

                        @if (_signInManager.IsSignedIn(User) && User.IsInRole("Staff"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="GetAllBookings">Booking</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="GetAllRooms">Rooms</a>
                            </li>
                         }
                        @if (_signInManager.IsSignedIn(User) && User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="GetAllBookings">Booking</a>
                                </li>
                        }
                    </ul>
                       <ul class="nav navbar-nav my-2 my-lg-0">


                        @if (_signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">logout @User.Identity.Name </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register"><i class="fas fa-user" ></i> Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login"><i class="fas fa-sign-in-alt" ></i> Login</a>
                        </li>
                        }*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HRBMSWEBAPP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HRBMSWEBAPP/Views/Shared/_Layoute.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> _signInManager



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>@ViewData["Title"] - HRBMSWEBAPP</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" asp-append-version="true">
    <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/vendor/quill/quill.snow.css" rel="stylesheet" asp-append-version="true">
    <link href="~/vendor/quill/quill.bubble.css" rel="stylesheet" asp-append-version="true">
    <link href="~/vendor/remixicon/remixicon.css" rel="stylesheet" asp-append-version="true">
    <link href="~/vendor/simple-datatables/style.css" rel="stylesheet" asp-append-version="true">
    <link rel="stylesheet" href="~/HRBMSWEBAPP.styles.css" asp-append-version="true" />

    <!--  Main CSS File -->
    <link href="~/css/stylesheet.css" rel="stylesheet" asp-append-version="true">
</head>
<body>
    <header id="header" class="header fixed-top d-flex align-items-center">
        <div class="d-flex align-items-center justify-content-between">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center">
                <img src="~/img/logo1.png" alt="">
                <span class="d-none d-lg-block">Hotel Booking System</span>
            </a>
          
            @if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
                <div style="padding: 20px">
                    <a class="nav-item" asp-area="" asp-controller="Users" asp-action="GetAllUsers">
                        <span>User</span>
                    </a>
                </div>
                <div style="padding: 20px">
                    <a class="nav-item" asp-area="" asp-controller="Booking" asp-action="GetAllBookings">
                        <span>Booking List</span>
                    </a>
                </div>
                <div style="padding: 20px">
                    <a class="nav-item" asp-area="" asp-controller="RoomCategory" asp-action="GetAllRoomCategories">
                        <span>Room Categories</span>
                    </a>
                </div>
                <div style="padding: 20px">
                    <a class="nav-item" asp-area="" asp-controller="Room" asp-action="GetAllRooms">
                        <span>Rooms List</span>
                    </a>
                </div>
               @* <div style="padding: 20px">
                    <a class="nav-item" asp-area="" asp-controller="Roles" asp-action="GetAllRoles">
                    <span>Users Roles</span>
                </a>
            </div>*@
            }
            @* <i class="bi bi-list toggle-sidebar-btn"></i>*@

        </div>

        <nav class="header-nav ms-auto">

            <ul class="d-flex align-items-center">
                @if (_signInManager.IsSignedIn(User))
                {
                    <li class="nav-item" style="padding: 20px">

                        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                           
                            <span class="d-none d-md-block ps-2"> Hello @(ViewBag.UserId)!</span><!--Edit Name of User-->
                        </a>
                    </li>
                    <li class="nav-item" style="padding: 20px">
                        <a  class="nav-link collapsed" asp-controller="Account" asp-action="Logout">
                            <i class="bi bi-box-arrow-in-right"></i>
                            <span>Sign Out</span>
                        </a>
                    </li>
                    <li class="nav-item" style="padding: 20px">
                        <a  class="nav-link collapsed" asp-controller="Account" asp-action="ChangePassword">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Change Password</span>
                        </a>
                    </li>



                        <!-- End Profile Dropdown Items -->
                   
                }
                else
                {

                    <li class="nav-item">
                        <a style="padding-right:10%" class="nav-link collapsed" asp-controller="Account" asp-action="Login">
                            <i class="bi bi-box-arrow-in-right"></i>
                            <span>Login</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a style="padding-right:10%" class="nav-link collapsed" asp-controller="Account" asp-action="Register">
                            <i class="bi bi-card-list"></i>
                            <span>Register</span>
                        </a>
                    </li>


                }
                  </ul>

        </nav>


        @if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
        {
            <aside id="sidebar" class="sidebar">

                <ul class="sidebar-nav" id="sidebar-nav">

                   @* <li class="nav-item">
                        <a class="nav-link " asp-controller="Home" asp-action="Index">
                            <!-- Insert Home page -->
                            <i class="bi bi-grid"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>*@

                    <li class="nav-item">
                        <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
                            <i class="bi bi-journal-text"></i><span>Add Forms</span><i class="bi bi-chevron-down ms-auto"></i>
                        </a>
                        <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                            <li>
                                <a asp-area="" asp-controller="Users" asp-action="Create">
                                    <i class="bi bi-circle"></i><span>Add User</span>
                                </a>
                            </li>

                            <li>
                                <a asp-area="" asp-controller="RoomCategory" asp-action="Create">
                                    <i class="bi bi-circle"></i><span>Add Category</span>
                                </a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Room" asp-action="Create">
                                    <i class="bi bi-circle"></i><span>Add Rooms</span>
                                </a>
                            </li>
                           @* <li>
                                <a asp-area="" asp-controller="Roles" asp-action="Create">
                                    <i class="bi bi-circle"></i><span>Add Roles</span>
                                </a>
                            </li>*@

                        </ul>
                    </li>
                </ul>

            </aside>
        }

            </header>

    @if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <div>
            <main role="main" id="main" class="main">

                @RenderBody()

            </main>
        </div>


        <footer id="footer" class="footer">
            <div class="copyright">
                &copy; Copyright <strong><span>Hotel Room Booking System</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                Designed by Ivhan and Mark
            </div>
        </footer>
    }
    else
    {
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="copyright">
                &copy; Copyright <strong><span>Hotel Room Booking System</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                Designed by Ivhan and Mark
            </div>
        </footer>
    }

    }
    <script src="~/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/chart.js/chart.umd.js"></script>
    <script src="~/vendor/echarts/echarts.min.js"></script>
    <script src="~/vendor/quill/quill.min.js"></script>
    <script src="~/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/vendor/tinymce/tinymce.min.js"></script>
    <script rc="~/js/site.js" asp-append-version="true"></script>

    <!-- Main JS File -->
    <script src="~/js/main.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>